In [1]:
import pandas as pd

# Opening a CSV File

In [2]:
df = pd.read_csv('D:/Important Files/Machine Learning/Datasets/IPL.csv').head(3)
df

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,second_ings_score,second_ings_wkts,match_winner,won_by,margin,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure
0,1,"March 26,2022","Wankhede Stadium, Mumbai",Chennai,Kolkata,Group,Kolkata,Field,131,5,133,4,Kolkata,Wickets,6,Umesh Yadav,MS Dhoni,50,Dwayne Bravo,3--20
1,2,"March 27,2022","Brabourne Stadium, Mumbai",Delhi,Mumbai,Group,Delhi,Field,177,5,179,6,Delhi,Wickets,4,Kuldeep Yadav,Ishan Kishan,81,Kuldeep Yadav,3--18
2,3,"March 27,2022","Dr DY Patil Sports Academy, Mumbai",Banglore,Punjab,Group,Punjab,Field,205,2,208,5,Punjab,Wickets,5,Odean Smith,Faf du Plessis,88,Mohammed Siraj,2--59

# Opening a CSV File from a URL

In [3]:
# import requests
# from io import StringIO

# url = ""
# headers = {"User-Agent": "Mozilla/5.0 (Macintosh: Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
# req = requests.get(url, headers=headers)
# data = StringIO(req.text)

# pd.read_csv(data)

# Sep Parameter
The thing on the basis of which the data in files are separated. Especially in TSV files

In [4]:
# pd.read_csv('IPL.csv', sep='\t')

# Naming the columns if they are missing

In [5]:
# pd.read_csv('IPL.csv', names=['serial no', 'name', 'etc', 'etc'])

# Index column parameter
To remove the default pandas index column

In [6]:
pd.read_csv('D:/Important Files/Machine Learning/Datasets/IPL.csv',index_col='match_id').head(1)

,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,second_ings_score,second_ings_wkts,match_winner,won_by,margin,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure
match_id,,,,,,,,,,,,,,,,,,,
1,"March 26,2022","Wankhede Stadium, Mumbai",Chennai,Kolkata,Group,Kolkata,Field,131,5,133,4,Kolkata,Wickets,6,Umesh Yadav,MS Dhoni,50,Dwayne Bravo,3--20

# Header Parameter
To fix the problem when column names are treated as rows. Just use headers=1

In [7]:
# pd.read_csv('IPL.csv',header=1).head(1)

# To use specific columns from entire dataset

In [8]:
pd.read_csv('D:/Important Files/Machine Learning/Datasets/IPL.csv',
            usecols=['match_id','venue','team1','team2','match_winner'],index_col='match_id').head(5)

,venue,team1,team2,match_winner
match_id,,,,
1,"Wankhede Stadium, Mumbai",Chennai,Kolkata,Kolkata
2,"Brabourne Stadium, Mumbai",Delhi,Mumbai,Delhi
3,"Dr DY Patil Sports Academy, Mumbai",Banglore,Punjab,Punjab
4,"Wankhede Stadium, Mumbai",Gujarat,Lucknow,Gujarat
5,"Maharashtra Cricket Association Stadium,Pune",Hyderabad,Rajasthan,Rajasthan

# Squeeze Parameter
Convert dataset from dataframe to dataseries

In [9]:
pd.read_csv('D:/Important Files/Machine Learning/Datasets/IPL.csv',usecols=['match_winner']).squeeze().head(5)

0      Kolkata
1        Delhi
2       Punjab
3      Gujarat
4    Rajasthan
Name: match_winner, dtype: object

# SkipRows/NRows Parameter

In [10]:
pd.read_csv('D:/Important Files/Machine Learning/Datasets/IPL.csv',skiprows=[0,2]).head(3)

,1,"March 26,2022","Wankhede Stadium, Mumbai",Chennai,Kolkata,Group,Kolkata.1,Field,131,5,133,4,Kolkata.2,Wickets,6,Umesh Yadav,MS Dhoni,50,Dwayne Bravo,3--20
0,3,"March 27,2022","Dr DY Patil Sports Academy, Mumbai",Banglore,Punjab,Group,Punjab,Field,205,2,208,5,Punjab,Wickets,5,Odean Smith,Faf du Plessis,88,Mohammed Siraj,2--59
1,4,"March 28,2022","Wankhede Stadium, Mumbai",Gujarat,Lucknow,Group,Gujarat,Field,158,6,161,5,Gujarat,Wickets,5,Mohammed Shami,Deepak Hooda,55,Mohammed Shami,3--25
2,5,"March 29,2022","Maharashtra Cricket Association Stadium,Pune",Hyderabad,Rajasthan,Group,Hyderabad,Field,210,6,149,7,Rajasthan,Runs,61,Sanju Samson,Aiden Markram,57,Yuzvendra Chahal,3--22

In [11]:
# nrows only import the number of rows from the dataset which is given to the parameter
pd.read_csv('D:/Important Files/Machine Learning/Datasets/IPL.csv',nrows=5)

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,second_ings_score,second_ings_wkts,match_winner,won_by,margin,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure
0,1,"March 26,2022","Wankhede Stadium, Mumbai",Chennai,Kolkata,Group,Kolkata,Field,131,5,133,4,Kolkata,Wickets,6,Umesh Yadav,MS Dhoni,50,Dwayne Bravo,3--20
1,2,"March 27,2022","Brabourne Stadium, Mumbai",Delhi,Mumbai,Group,Delhi,Field,177,5,179,6,Delhi,Wickets,4,Kuldeep Yadav,Ishan Kishan,81,Kuldeep Yadav,3--18
2,3,"March 27,2022","Dr DY Patil Sports Academy, Mumbai",Banglore,Punjab,Group,Punjab,Field,205,2,208,5,Punjab,Wickets,5,Odean Smith,Faf du Plessis,88,Mohammed Siraj,2--59
3,4,"March 28,2022","Wankhede Stadium, Mumbai",Gujarat,Lucknow,Group,Gujarat,Field,158,6,161,5,Gujarat,Wickets,5,Mohammed Shami,Deepak Hooda,55,Mohammed Shami,3--25
4,5,"March 29,2022","Maharashtra Cricket Association Stadium,Pune",Hyderabad,Rajasthan,Group,Hyderabad,Field,210,6,149,7,Rajasthan,Runs,61,Sanju Samson,Aiden Markram,57,Yuzvendra Chahal,3--22

# Encoding Parameter
Used when the format of dataset isn't UTF8. Either change the encoding of the dataset in any editor such as sublime editor or you can find out the encoding of the dataset and then write it in the parameter

In [12]:
# pd.read_csv('D:/Important Files/Machine Learning/Datasets/IPL.csv', encoding='latin-1')

# Skip bad lines
Ignore the rows which have higher number of row values than the number of its column

In [13]:
# pd.read_csv('D:/Important Files/Machine Learning/Datasets/IPL.csv',error_bad_lines = False)

# Dtypes Parameter
Use to change the datatype of a specific column in a dataset

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   match_id             3 non-null      int64
 1   date                 3 non-null      object
 2   venue                3 non-null      object
 3   team1                3 non-null      object
 4   team2                3 non-null      object
 5   stage                3 non-null      object
 6   toss_winner          3 non-null      object
 7   toss_decision        3 non-null      object
 8   first_ings_score     3 non-null      int64
 9   first_ings_wkts      3 non-null      int64
 10  second_ings_score    3 non-null      int64
 11  second_ings_wkts     3 non-null      int64
 12  match_winner         3 non-null      object
 13  won_by               3 non-null      object
 14  margin               3 non-null      int64
 15  player_of_the_match  3 non-null      object
 16  top_scorer           3 non-null      object
 17  highscore            3 non-null      int64
 18  best_bowling         3 non-null      object
 19  best_bowling_figure  3 non-null      object
dtypes: int64(7), object(13)
memory usage: 612.0+ bytes

In [15]:
pd.read_csv('D:/Important Files/Machine Learning/Datasets/IPL.csv',dtype={'match_id':int}).head(1)

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,second_ings_score,second_ings_wkts,match_winner,won_by,margin,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure
0,1,"March 26,2022","Wankhede Stadium, Mumbai",Chennai,Kolkata,Group,Kolkata,Field,131,5,133,4,Kolkata,Wickets,6,Umesh Yadav,MS Dhoni,50,Dwayne Bravo,3--20

# Handling Dates
Changing the datatype of date time columns to apply date logics on it which cannot be applied on it if its data type is string. This parameter can also be used to merge different date columns into one such as combining day, month and year colums into one as date column

In [16]:
pd.read_csv('D:/Important Files/Machine Learning/Datasets/IPL.csv').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   match_id             74 non-null     int64
 1   date                 74 non-null     object
 2   venue                74 non-null     object
 3   team1                74 non-null     object
 4   team2                74 non-null     object
 5   stage                74 non-null     object
 6   toss_winner          74 non-null     object
 7   toss_decision        74 non-null     object
 8   first_ings_score     74 non-null     int64
 9   first_ings_wkts      74 non-null     int64
 10  second_ings_score    74 non-null     int64
 11  second_ings_wkts     74 non-null     int64
 12  match_winner         74 non-null     object
 13  won_by               74 non-null     object
 14  margin               74 non-null     int64
 15  player_of_the_match  74 non-null     object
 16  top_scorer           74 non-null     object
 17  highscore            74 non-null     int64
 18  best_bowling         74 non-null     object
 19  best_bowling_figure  74 non-null     object
dtypes: int64(7), object(13)
memory usage: 11.7+ KB

In [17]:
pd.read_csv('D:/Important Files/Machine Learning/Datasets/IPL.csv',parse_dates=['date']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   match_id             74 non-null     int64
 1   date                 74 non-null     object
 2   venue                74 non-null     object
 3   team1                74 non-null     object
 4   team2                74 non-null     object
 5   stage                74 non-null     object
 6   toss_winner          74 non-null     object
 7   toss_decision        74 non-null     object
 8   first_ings_score     74 non-null     int64
 9   first_ings_wkts      74 non-null     int64
 10  second_ings_score    74 non-null     int64
 11  second_ings_wkts     74 non-null     int64
 12  match_winner         74 non-null     object
 13  won_by               74 non-null     object
 14  margin               74 non-null     int64
 15  player_of_the_match  74 non-null     object
 16  top_scorer           74 non-null     object
 17  highscore            74 non-null     int64
 18  best_bowling         74 non-null     object
 19  best_bowling_figure  74 non-null     object
dtypes: int64(7), object(13)
memory usage: 11.7+ KB

C:\Users\Talha Ahmad\AppData\Local\Temp\ipykernel_8840\294116167.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.read_csv('D:/Important Files/Machine Learning/Datasets/IPL.csv',parse_dates=['date']).info()

# Converters
Use to change the contents in a specific column like shortening the names etc

In [18]:
pd.read_csv('D:/Important Files/Machine Learning/Datasets/IPL.csv').head(3)

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,second_ings_score,second_ings_wkts,match_winner,won_by,margin,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure
0,1,"March 26,2022","Wankhede Stadium, Mumbai",Chennai,Kolkata,Group,Kolkata,Field,131,5,133,4,Kolkata,Wickets,6,Umesh Yadav,MS Dhoni,50,Dwayne Bravo,3--20
1,2,"March 27,2022","Brabourne Stadium, Mumbai",Delhi,Mumbai,Group,Delhi,Field,177,5,179,6,Delhi,Wickets,4,Kuldeep Yadav,Ishan Kishan,81,Kuldeep Yadav,3--18
2,3,"March 27,2022","Dr DY Patil Sports Academy, Mumbai",Banglore,Punjab,Group,Punjab,Field,205,2,208,5,Punjab,Wickets,5,Odean Smith,Faf du Plessis,88,Mohammed Siraj,2--59

In [19]:
def rename(name):
    if name == 'Wankhede Stadium, Mumbai':
        return 'WS,M'
    if name == 'Brabourne Stadium, Mumbai':
        return 'BS,M'
    else:
        return name

pd.read_csv('D:/Important Files/Machine Learning/Datasets/IPL.csv',converters={'venue':rename}).head(5)

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,second_ings_score,second_ings_wkts,match_winner,won_by,margin,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure
0,1,"March 26,2022","WS,M",Chennai,Kolkata,Group,Kolkata,Field,131,5,133,4,Kolkata,Wickets,6,Umesh Yadav,MS Dhoni,50,Dwayne Bravo,3--20
1,2,"March 27,2022","BS,M",Delhi,Mumbai,Group,Delhi,Field,177,5,179,6,Delhi,Wickets,4,Kuldeep Yadav,Ishan Kishan,81,Kuldeep Yadav,3--18
2,3,"March 27,2022","Dr DY Patil Sports Academy, Mumbai",Banglore,Punjab,Group,Punjab,Field,205,2,208,5,Punjab,Wickets,5,Odean Smith,Faf du Plessis,88,Mohammed Siraj,2--59
3,4,"March 28,2022","WS,M",Gujarat,Lucknow,Group,Gujarat,Field,158,6,161,5,Gujarat,Wickets,5,Mohammed Shami,Deepak Hooda,55,Mohammed Shami,3--25
4,5,"March 29,2022","Maharashtra Cricket Association Stadium,Pune",Hyderabad,Rajasthan,Group,Hyderabad,Field,210,6,149,7,Rajasthan,Runs,61,Sanju Samson,Aiden Markram,57,Yuzvendra Chahal,3--22

# NA_Values Parameter
Used when in some datasets the null values are represented in some other formats such as hyphon '-' or in something else

In [20]:
pd.read_csv('D:/Important Files/Machine Learning/Datasets/IPL.csv',na_values=['-']).head(3)

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,second_ings_score,second_ings_wkts,match_winner,won_by,margin,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure
0,1,"March 26,2022","Wankhede Stadium, Mumbai",Chennai,Kolkata,Group,Kolkata,Field,131,5,133,4,Kolkata,Wickets,6,Umesh Yadav,MS Dhoni,50,Dwayne Bravo,3--20
1,2,"March 27,2022","Brabourne Stadium, Mumbai",Delhi,Mumbai,Group,Delhi,Field,177,5,179,6,Delhi,Wickets,4,Kuldeep Yadav,Ishan Kishan,81,Kuldeep Yadav,3--18
2,3,"March 27,2022","Dr DY Patil Sports Academy, Mumbai",Banglore,Punjab,Group,Punjab,Field,205,2,208,5,Punjab,Wickets,5,Odean Smith,Faf du Plessis,88,Mohammed Siraj,2--59

#  Loading a huge dataset in chunks

In [21]:
dfs = pd.read_csv('D:/Important Files/Machine Learning/Datasets/IPL.csv',chunksize=20)
dfs

In [22]:
for chunks in dfs:
    print(chunks.shape)

(20, 20)
(20, 20)
(20, 20)
(14, 20)