In [1]:
import numpy as np
import pandas as pd

# Group By

In [2]:
df = pd.DataFrame({
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 130, 200, 300],
    'Quantity': [10, 15, 12, 20, 8, 9, 15, 25],
    'Data': pd.date_range('2026-07-18', periods=8)
})
df

  Category Store  Sales  Quantity       Data
0        A    S1    100        10 2026-07-18
1        B    S1    200        15 2026-07-19
2        A    S2    150        12 2026-07-20
3        B    S2    250        20 2026-07-21
4        A    S1    120         8 2026-07-22
5        B    S2    130         9 2026-07-23
6        A    S2    200        15 2026-07-24
7        B    S1    300        25 2026-07-25

In [3]:
df.groupby('Category')

In [4]:
df.groupby('Category')['Sales'].sum()

Category
A    570
B    880
Name: Sales, dtype: int64

In [5]:
group = df.groupby('Store')
for i, v in group:
    print(i)
    print(v)

S1
  Category Store  Sales  Quantity       Data
0        A    S1    100        10 2026-07-18
1        B    S1    200        15 2026-07-19
4        A    S1    120         8 2026-07-22
7        B    S1    300        25 2026-07-25
S2
  Category Store  Sales  Quantity       Data
2        A    S2    150        12 2026-07-20
3        B    S2    250        20 2026-07-21
5        B    S2    130         9 2026-07-23
6        A    S2    200        15 2026-07-24

In [7]:
df.groupby('Store')['Sales'].sum()

Store
S1    720
S2    730
Name: Sales, dtype: int64

In [12]:
df.groupby(['Category', 'Store'])['Sales'].sum()

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       380
Name: Sales, dtype: int64

In [13]:
df.groupby(['Store', 'Category'])['Sales'].sum()

Store  Category
S1     A           220
       B           500
S2     A           350
       B           380
Name: Sales, dtype: int64

# Aggregation

In [14]:
df

  Category Store  Sales  Quantity       Data
0        A    S1    100        10 2026-07-18
1        B    S1    200        15 2026-07-19
2        A    S2    150        12 2026-07-20
3        B    S2    250        20 2026-07-21
4        A    S1    120         8 2026-07-22
5        B    S2    130         9 2026-07-23
6        A    S2    200        15 2026-07-24
7        B    S1    300        25 2026-07-25

In [19]:
df['Sales'].mean()

np.float64(181.25)

In [20]:
df['Sales'].std()

np.float64(69.16594950861712)

In [21]:
df['Sales'].mode()

0    200
Name: Sales, dtype: int64

In [28]:
df['Sales'].agg(['sum', 'mean', 'min', 'max', 'count', 'std', 'median', 'mean'])

sum       1450.00000
mean       181.25000
min        100.00000
max        300.00000
count        8.00000
std         69.16595
median     175.00000
mean       181.25000
Name: Sales, dtype: float64