In [1]:
import numpy as np
import pandas as pd

# Merging 2 Databases

In [2]:
employees = pd.DataFrame({
    'employee_id': [1,2,3,4,5],
    'name': ['John','Anna','Peter','Linda','Bob'],
    'department': ['HR','IT','Finance','IT','HR']
})

salaries = pd.DataFrame({
    'employee_id': [1,2,3,6,7],
    'salaries': [60000, 62000, 65000, 70000, 76000],
    'bonus': [5000, 10000, 8000, 12000, 7000]
})

In [3]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [4]:
salaries

   employee_id  salaries  bonus
0            1     60000   5000
1            2     62000  10000
2            3     65000   8000
3            6     70000  12000
4            7     76000   7000

In [5]:
pd.merge(employees, salaries, on='employee_id', how='inner')

   employee_id   name department  salaries  bonus
0            1   John         HR     60000   5000
1            2   Anna         IT     62000  10000
2            3  Peter    Finance     65000   8000

In [6]:
pd.merge(employees, salaries, on='employee_id', how='outer')

   employee_id   name department  salaries    bonus
0            1   John         HR   60000.0   5000.0
1            2   Anna         IT   62000.0  10000.0
2            3  Peter    Finance   65000.0   8000.0
3            4  Linda         IT       NaN      NaN
4            5    Bob         HR       NaN      NaN
5            6    NaN        NaN   70000.0  12000.0
6            7    NaN        NaN   76000.0   7000.0

In [7]:
pd.merge(employees, salaries, on='employee_id', how='left')

   employee_id   name department  salaries    bonus
0            1   John         HR   60000.0   5000.0
1            2   Anna         IT   62000.0  10000.0
2            3  Peter    Finance   65000.0   8000.0
3            4  Linda         IT       NaN      NaN
4            5    Bob         HR       NaN      NaN

In [8]:
pd.merge(employees, salaries, on='employee_id', how='right')

   employee_id   name department  salaries  bonus
0            1   John         HR     60000   5000
1            2   Anna         IT     62000  10000
2            3  Peter    Finance     65000   8000
3            6    NaN        NaN     70000  12000
4            7    NaN        NaN     76000   7000

# Concatenation of 2 Databases

In [9]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [10]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [11]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [12]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [13]:
pd.concat([df1,df2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

# Joining of 2 Databases

In [18]:
Df1 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie']
}, index= [1,2,3])

Df2 = pd.DataFrame({
    'Score': [85, 90, 75]
}, index=[2,3,4])

In [19]:
Df1

      Name
1    Alice
2      Bob
3  Charlie

In [20]:
Df2

   Score
2     85
3     90
4     75

In [21]:
Df1.join(Df2)

      Name  Score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [23]:
Df1.join(Df2,how='outer')

      Name  Score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [25]:
Df1.join(Df2,how='right')

      Name  Score
2      Bob     85
3  Charlie     90
4      NaN     75