In [1]:
import numpy as np
import pandas as pd

# Pivot Table

In [2]:
data = {
    'Date': pd.date_range('2026-07-18', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South'] * 5,
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice'] * 5
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep   Month Quarter
0  2026-07-18       A   East    253     19   John    July      Q3
1  2026-07-19       B   West    712     15   Mary    July      Q3
2  2026-07-20       C  North    626     90    Bob    July      Q3
3  2026-07-21       D  South    216     98  Alice    July      Q3
4  2026-07-22       A   East    170     98   John    July      Q3
5  2026-07-23       B   West    782     16   Mary    July      Q3
6  2026-07-24       C  North    236     81    Bob    July      Q3
7  2026-07-25       D  South    130     78  Alice    July      Q3
8  2026-07-26       A   East    956     54   John    July      Q3
9  2026-07-27       B   West    726     41   Mary    July      Q3
10 2026-07-28       C  North    221     50    Bob    July      Q3
11 2026-07-29       D  South    438     86  Alice    July      Q3
12 2026-07-30       A   East    788     22   John    July      Q3
13 2026-07-31       B   West    398     21   Mary    July      Q3
14 2026-08-01       C  North    295     33    Bob  August      Q3
15 2026-08-02       D  South    100     25  Alice  August      Q3
16 2026-08-03       A   East    658     16   John  August      Q3
17 2026-08-04       B   West    584     28   Mary  August      Q3
18 2026-08-05       C  North    501     46    Bob  August      Q3
19 2026-08-06       D  South    751     24  Alice  August      Q3

In [3]:
pd.pivot_table(df, values = 'Sales', index= 'Region', columns='Product')

Product      A      B      C      D
Region
East     565.0    NaN    NaN    NaN
North      NaN    NaN  375.8    NaN
South      NaN    NaN    NaN  327.0
West       NaN  640.4    NaN    NaN

In [4]:
pd.pivot_table(df, values = 'Sales', index= 'Region', columns='Product',aggfunc='median')

Product      A      B      C      D
Region
East     658.0    NaN    NaN    NaN
North      NaN    NaN  295.0    NaN
South      NaN    NaN    NaN  216.0
West       NaN  712.0    NaN    NaN

In [5]:
df

         Date Product Region  Sales  Units    Rep   Month Quarter
0  2026-07-18       A   East    253     19   John    July      Q3
1  2026-07-19       B   West    712     15   Mary    July      Q3
2  2026-07-20       C  North    626     90    Bob    July      Q3
3  2026-07-21       D  South    216     98  Alice    July      Q3
4  2026-07-22       A   East    170     98   John    July      Q3
5  2026-07-23       B   West    782     16   Mary    July      Q3
6  2026-07-24       C  North    236     81    Bob    July      Q3
7  2026-07-25       D  South    130     78  Alice    July      Q3
8  2026-07-26       A   East    956     54   John    July      Q3
9  2026-07-27       B   West    726     41   Mary    July      Q3
10 2026-07-28       C  North    221     50    Bob    July      Q3
11 2026-07-29       D  South    438     86  Alice    July      Q3
12 2026-07-30       A   East    788     22   John    July      Q3
13 2026-07-31       B   West    398     21   Mary    July      Q3
14 2026-08-01       C  North    295     33    Bob  August      Q3
15 2026-08-02       D  South    100     25  Alice  August      Q3
16 2026-08-03       A   East    658     16   John  August      Q3
17 2026-08-04       B   West    584     28   Mary  August      Q3
18 2026-08-05       C  North    501     46    Bob  August      Q3
19 2026-08-06       D  South    751     24  Alice  August      Q3

In [6]:
pd.pivot_table(df, values = ['Sales', 'Units'], index= 'Region', columns='Product')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     565.0    NaN    NaN    NaN  41.8   NaN   NaN   NaN
North      NaN    NaN  375.8    NaN   NaN   NaN  60.0   NaN
South      NaN    NaN    NaN  327.0   NaN   NaN   NaN  62.2
West       NaN  640.4    NaN    NaN   NaN  24.2   NaN   NaN

# Cross Tables

In [7]:
pd.crosstab(df['Region'], df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0