In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('D:/Important Files/Machine Learning/Datasets/train.csv').drop(columns=['PassengerId','Pclass','Name','Sex','Ticket','Embarked'])
df.head(5)

   Survived   Age  SibSp  Parch     Fare Cabin
0         0  22.0      1      0   7.2500   NaN
1         1  38.0      1      0  71.2833   C85
2         1  26.0      0      0   7.9250   NaN
3         1  35.0      1      0  53.1000  C123
4         0  35.0      0      0   8.0500   NaN

In [3]:
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
df[['SibSp', 'Parch', 'FamilySize']].head()

   SibSp  Parch  FamilySize
0      1      0           2
1      1      0           2
2      0      0           1
3      1      0           2
4      0      0           1

## 3. Binary / Flag Features:

### a. Is Alone:

In [4]:
df['IsAlone'] = (df['FamilySize'] == 1).astype(int)
df[['FamilySize', 'IsAlone']].head()

   FamilySize  IsAlone
0           2        0
1           2        0
2           1        1
3           2        0
4           1        1

### b. Is Child:

In [5]:
df['IsChild'] = (df['Age'] < 18).astype(int)
df[['Age', 'IsChild']].head()

    Age  IsChild
0  22.0        0
1  38.0        0
2  26.0        0
3  35.0        0
4  35.0        0

### c. Has Cabin Recorded:

In [6]:
df['HasCabin'] = df['Cabin'].notna().astype(int)
df[['Cabin', 'HasCabin']].head()

  Cabin  HasCabin
0   NaN         0
1   C85         1
2   NaN         0
3  C123         1
4   NaN         0

### d. Is High Fare:

In [7]:
fare_75th = df['Fare'].quantile(0.75)
df['IsHighFare'] = (df['Fare'] > fare_75th).astype(int)
df[['Fare', 'IsHighFare']].head()

      Fare  IsHighFare
0   7.2500           0
1  71.2833           1
2   7.9250           0
3  53.1000           1
4   8.0500           0

In [8]:
df.sample(5)

,Survived,Age,SibSp,Parch,Fare,Cabin,FamilySize,IsAlone,IsChild,HasCabin,IsHighFare
692,1,NaN,0,0,56.4958,NaN,1,1,0,0,1
823,1,27.0,0,1,12.4750,E121,2,0,0,1,0
513,1,54.0,1,0,59.4000,NaN,2,0,0,0,1
88,1,23.0,3,2,263.0000,C23 C25 C27,6,0,0,1,1
402,0,21.0,1,0,9.8250,NaN,2,0,0,0,0