In [7]:
import pandas as pd
import numpy as np

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [2]:
df = pd.read_csv('D:/Important Files/Machine Learning/Datasets/train.csv')[['Age','Pclass','SibSp','Parch','Survived']]
df.head(5)

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [3]:
df.dropna(inplace=True)

In [4]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [5]:
X.head()

    Age  Pclass  SibSp  Parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [6]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [12]:
np.mean(cross_val_score(LogisticRegression(), X, y, scoring='accuracy', cv=20))

np.float64(0.6933333333333332)

## Feature Construction:

In [28]:
X['family_size'] = X['SibSp'] + X['Parch'] + 1
X.head()

    Age  Pclass  SibSp  Parch  family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [29]:
def size(num):
    if num == 1:
        return 0
    elif num > 1 and num <= 4:
        return 1
    else:
        return 2

In [30]:
X['family_type'] = X['family_size'].apply(size)

In [31]:
X.sample(10)

      Age  Pclass  SibSp  Parch  family_size  family_type
96   71.0       1      0      0            1            0
153  40.5       3      0      2            3            1
514  24.0       3      0      0            1            0
199  24.0       2      0      0            1            0
523  44.0       1      0      1            2            1
691   4.0       3      0      1            2            1
43    3.0       2      1      2            4            1
135  23.0       2      0      0            1            0
515  47.0       1      0      0            1            0
453  49.0       1      1      0            2            1

In [32]:
X.drop(columns=['SibSp','Parch','family_size'],inplace=True)

In [33]:
X.head()

    Age  Pclass  family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [34]:
np.mean(cross_val_score(LogisticRegression(), X, y, scoring='accuracy', cv=20))

np.float64(0.7003174603174602)