In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

In [2]:
df = pd.read_csv('D:/Important Files/Machine Learning/Datasets/train.csv').drop(columns=['PassengerId','Survived','SibSp','Parch','Pclass','Name','Sex','Ticket','Embarked','Cabin'])
df.head(5)

    Age     Fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

## 5. Polynomial Features:
Using `Age` and `Fare` as the base numeric columns.

In [3]:
poly_df = df[['Age', 'Fare']].dropna()

In [4]:
poly = PolynomialFeatures(degree=2, include_bias=False)
poly_features = poly.fit_transform(poly_df)

In [5]:
poly_feature_names = poly.get_feature_names_out(['Age', 'Fare'])

In [6]:
poly_result = pd.DataFrame(poly_features, columns=poly_feature_names, index=poly_df.index)
poly_result.head()

    Age     Fare   Age^2   Age Fare       Fare^2
0  22.0   7.2500   484.0   159.5000    52.562500
1  38.0  71.2833  1444.0  2708.7654  5081.308859
2  26.0   7.9250   676.0   206.0500    62.805625
3  35.0  53.1000  1225.0  1858.5000  2819.610000
4  35.0   8.0500  1225.0   281.7500    64.802500