In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [ ]:
df = pd.read_csv('D:/Important Files/Machine Learning/Datasets/train.csv',
                 usecols=['Survived','Pclass','Sex','Age','SibSp','Parch','Fare','Embarked'])
df.head(5)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [3]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Survived']),df['Survived'],test_size=0.2,random_state=42)

In [4]:
X_train.head(5)

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [5]:
y_train.head(5)

331    0
733    0
382    0
704    0
813    0
Name: Survived, dtype: int64

In [6]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [7]:
si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')

X_train_age = si_age.fit_transform(X_train[['Age']])
X_train_embarked = si_embarked.fit_transform(X_train[['Embarked']])

X_test_age = si_age.transform(X_test[['Age']])
X_test_embarked = si_embarked.transform(X_test[['Embarked']])

In [8]:
ohe_sex = OneHotEncoder(sparse_output=False,handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse_output=False,handle_unknown='ignore')

X_train_sex = ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked = ohe_embarked.fit_transform(X_train_embarked)

X_test_sex = ohe_sex.transform(X_test[['Sex']])
X_test_embarked = ohe_embarked.transform(X_test_embarked)

In [9]:
X_train_sex

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]], shape=(712, 2))

In [10]:
X_train_embarked

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]], shape=(712, 3))

In [11]:
X_train_rem = X_train.drop(columns=['Age','Sex','Embarked'])
X_test_rem = X_test.drop(columns=['Age','Sex','Embarked'])

In [12]:
X_train_transform = np.concatenate((X_train_rem,X_train_age,X_train_sex,X_train_embarked),axis=1)
X_test_transform = np.concatenate((X_test_rem,X_test_age,X_test_sex,X_test_embarked),axis=1)

In [13]:
X_train_transform.shape

(712, 10)

In [14]:
clf = DecisionTreeClassifier()

clf.fit(X_train_transform,y_train)
y_pred = clf.predict(X_test_transform)

accuracy_score(y_test,y_pred)

0.7877094972067039

In [15]:
import os
import pickle

os.makedirs('Models', exist_ok=True)

pickle.dump(ohe_sex,open('Models/ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('Models/ohe_embarked.pkl','wb'))
pickle.dump(clf,open('Models/clf.pkl','wb'))